#!/usr/bin/env php
<?php

require_once('adminutil.php');
includeAdd(getParent());

require_once('Net/OpenID/CryptUtil.php');

$lib =& Net_OpenID_MathLibrary::getLibWrapper();

if ($lib === null) {
    fwrite(STDERR, 'No math library present\n');
    exit(1);
} else {
    print $lib->type;
}

?>
